{{- if .Values.alertmanager.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "infoworks.fullname" . }}-governor
  namespace: {{ template "infoworks.namespace" . }}
  labels:
    app: {{ template "infoworks.fullname" . }}-governor
spec:
  replicas: {{ .Values.infoworks-ui.replicas }}
  selector:
    matchLabels:
      app: {{ template "infoworks.fullname" . }}-governor
  template:
    metadata:
      labels:
        app: {{ template "infoworks.fullname" . }}-governor
    spec:
      containers:
        - name: {{ .Chart.Name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.infoworksgovernor.image }}
          image: {{ .Values.infoworksgovernor.image.repository }}:{{ .Values.infoworksgovernor.image.tag }}
          version: {{ .Values.infoworksgovernor.image.tag }}
          {{- end }}
          ports:
            - containerPort: 3002
              name: http
