apiVersion: v1
kind: Service
metadata:
  name: {{ template "infoworks.fullname" . }}-governor
  namespace: {{ template "infoworks.namespace" . }}
  labels:
    app: {{ template "infoworks.fullname" . }}-governor
spec:
  type: {{ .Values.infoworksgovernor.service.type }}
  ports:
    - port: {{ .Values.infoworksgovernor.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "infoworks.fullname" . }}-governor
